### ISSUE TITLE
DllNotFoundException

### ISSUE THREAD

**Issue by mustafashabib** [brandonc/moonshine#3]
Hey There

We're trying to deploy into a 64bit environment on an asp.net mvc 3 app running in IIS 7 and we're seeing this problem. The libsundown.dll is in our bin folder and we compiled to target the x86 platform.

Here's the exception from our event log:

```
Exception information: 
    Exception type: DllNotFoundException 
    Exception message: Unable to load DLL 'libsundown.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Sundown.MoonShine.bufnew(UInt32 size)
   at Sundown.MoonShine.Markdownify(String s, MarkdownExtensions extensions, Boolean smartypants)
```

Any ideas?

**Comment by mustafashabib** [comment]
Hey All - 

To solve this issue, we had to 
1. install the x86 VC++ Redistributable  http://www.microsoft.com/en-us/download/details.aspx?id=5555
2. copy msvcr100.dll from c:\windows\syswow64 to c:\windows\system32

Hope that helps someone out there.

Mustafa
